### ISSUE TITLE
License & Copyright

### ISSUE THREAD

**Issue by qmfrederik** [Dixin/EnterpriseLibrary.TransientFaultHandling.Core#1]
I've noticed that you license this library under the MIT license, and state yourself as the copyright owner.

However, the upstream sources are licensed under the terms of the Apache License and list Microsoft as the copyright holder - see https://github.com/MicrosoftArchive/transient-fault-handling-application-block/blob/master/LICENSE.txt.

Are you sure that's correct? I'm asking because I'd like to redistribute this library with my application, but want to be sure the license & copyright information is correct.

**Comment by Dixin** [comment]
Thank you for your feed back. As I mentioned in the document, I ported some code from the upstream, and added new APIs, and redesign/reimplemented some code since they cannot work with .NET Core.

I am looking into the license issue.

**Comment by Dixin** [comment]
After looking into these licenses and discussing with many people, I believe there is no problems with this. MIT license and Apache License are both "do whatever & don't sue me" licenses. There is no conflict.
