### ISSUE TITLE
Missing SQL transient error

### ISSUE THREAD

**Issue by ErikEJ** [Dixin/EnterpriseLibrary.TransientFaultHandling.Core#4]
https://github.com/dotnet/efcore/issues/20923

and maybe look at differences between https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs
and  https://github.com/Dixin/EnterpriseLibrary.TransientFaultHandling.Core/blob/master/Source/TransientFaultHandling.Data.Core/SqlDatabaseTransientErrorDetectionStrategy.cs

**Comment by Dixin** [comment]
Thank you for bring this up! I have fix this and release a new version: https://www.nuget.org/packages/TransientFaultHandling.Data/.
