### ISSUE TITLE
The package can't be used in a net48 project

### ISSUE THREAD

**Issue by mcenzato** [Dixin/EnterpriseLibrary.TransientFaultHandling.Core#5]
May be I'm wrong, but as far as I know a netstandard20 package can be used in a net48 project.

When using the library in a net48 project a Code Access Security exception is thrown:

- Type:    System.TypeAccessException
- Message: Attempt by security transparent method 'Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.SqlDatabaseTransientErrorDetectionStrategy.IsTransient(System.Exception)' to access security critical type 'Microsoft.Data.SqlClient.SqlException' failed.

I've attached a small console application: changing target framework from net5.0 to net48 you can see the problem. 

[ReproCode.zip](https://github.com/Dixin/EnterpriseLibrary.TransientFaultHandling.Core/files/6873541/ReproCode.zip)

**Comment by Sossenbinder** [comment]
The problem is coming from

https://github.com/Dixin/EnterpriseLibrary.TransientFaultHandling.Core/blob/bee3f1d5138e186a96f1b8dd50dbb14c97b1bec2/Source/TransientFaultHandling.Core/TransientFaultHandling.Core.csproj#L31

https://github.com/Dixin/EnterpriseLibrary.TransientFaultHandling.Core/blob/master/Tools/AssemblyInfo.cs

The referenced AssemblyInfo pulls in the SecuritTransparent assembly attribute it seems

**Comment by mcenzato** [comment]
Hi @Sossenbinder , thanks for the reply!

I am not an expert (to tell the truth I don't know anything about Code Access Security apart from the fact that NET Core doesn't manage it): can I solve the problem in my code or it's a package problem?
May be the in the package source code the line
`[assembly: SecurityTransparent] ` 
in [https://github.com/Dixin/EnterpriseLibrary.TransientFaultHandling.Core/blob/master/Tools/AssemblyInfo.cs](https://github.com/Dixin/EnterpriseLibrary.TransientFaultHandling.Core/blob/master/Tools/AssemblyInfo.cs)
need to be wrapped with
```
#if #NETCOREAPP
...
#endif
```
?

**Comment by Sossenbinder** [comment]
I could imagine that works, honestly, I'm not in-depth enough to really tell how to fix it for good. For now I forked the lib and removed the line altogether.

What I'm pretty sure about is that you can't solve this in your code - I absolutely doubt that you could somehow configure an external assembly in your code to scale down its security settings, that would sound like a major security flaw to me and would make the feature useless 😄

**Comment by Dixin** [comment]
Thank you very much @mcenzato @Sossenbinder. I have fix this and released a new version: https://www.nuget.org/packages/EnterpriseLibrary.TransientFaultHandling.Core/.

**Comment by Sossenbinder** [comment]
Great, thanks!

**Comment by mcenzato** [comment]
Thanks very much Dixin!
